### ISSUE TITLE
Symbol not found: _iconv_open

### ISSUE THREAD

**Issue by c007136** [gollum/rugged_adapter#27]
Hi,

I run:`gollum --adapter rugged`
then open "localhost:4567" in my browser, but failed, error info is:

> == Sinatra (v1.4.8) has taken the stage on 4567 for development with backup from WEBrick
> [2017-02-16 15:41:53] INFO  WEBrick::HTTPServer#start: pid=15669 port=4567
> localhost - - [16/Feb/2017:15:42:08 CST] "GET / HTTP/1.1" 302 0
> - -> /
> dyld: lazy symbol binding failed: Symbol not found: _iconv_open
>  Referenced from: /opt/local/lib/ruby2.1/gems/2.1.0/gems/rugged-0.24.6.1/lib/rugged/rugged.bundle`
>  Expected in: flat namespace

> dyld: Symbol not found: _iconv_open
>   Referenced from: /opt/local/lib/ruby2.1/gems/2.1.0/gems/rugged-0.24.6.1/lib/rugged/rugged.bundle`
>   Expected in: flat namespace

> fish: 'gollum --adapter rugged' terminated by signal SIGABRT (Abort)

thanks.

**Comment by dometto** [comment]
This seems to be a local problem with your installation of `libdyld`. See for instance http://stackoverflow.com/questions/15678546/git-dyld-lazy-symbol-binding-failed-symbol-not-found-iconv-open . I'll close this, but you could try opening a stack overflow issue yourself. If there is any reason to think this bug is specific to the rugged adapter, please let us know and I'll reopen.
